import { IProduct, ProductCard } from '@/entities/product';
import styles from './ProductList.module.scss';
import { CatalogPagination } from '@/features/catalog-pagination';
import { ICatalogSearchParams } from '@/shared/types';
import { LoadMoreButton } from '@/features/catalog-load-more';

const BASE_LIMIT = 24;

export function ProductList({ searchParams }: ICatalogSearchParams) {
	const products: IProduct[] = [
		{
			id: 1,
			name: 'Scarlett Pump',
			category: 'Pumps',
			description: 'Elegant pump for evening events',
			image: '/images/placeholder.png',
			price: 2499,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'red'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
		{
			id: 2,
			name: 'Luna Stiletto',
			category: 'Stilettos',
			description: 'Classic stiletto with pointed toe',
			image: '/images/placeholder.png',
			price: 3199,
			sizes: [36, 37, 38, 39],
			colors: ['beige', 'black'],
			heelParams: '12 см (Professional)',
			material: 'Suede',
		},
		{
			id: 3,
			name: 'Nova Mule',
			category: 'Mules',
			description: 'Comfortable mule for everyday wear',
			image: '/images/placeholder.png',
			price: 1899,
			sizes: [37, 38, 39, 40, 41],
			colors: ['white', 'brown'],
			heelParams: '5 см (Casual)',
			material: 'Leather',
		},
		{
			id: 4,
			name: 'Aurora Sandal',
			category: 'Sandals',
			description: 'Light sandal for summer days',
			image: '/images/placeholder.png',
			price: 1599,
			sizes: [36, 37, 38, 39, 40],
			colors: ['gold', 'silver'],
			heelParams: '7 см (Casual)',
			material: 'Synthetic',
		},
		{
			id: 5,
			name: 'Stella Boot',
			category: 'Boots',
			description: 'Elegant ankle boot for autumn',
			image: '/images/placeholder.png',
			price: 4299,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'brown'],
			heelParams: '8 см (Professional)',
			material: 'Leather',
		},
		{
			id: 6,
			name: 'Iris Flat',
			category: 'Flats',
			description: 'Comfortable flat for daily use',
			image: '/images/placeholder.png',
			price: 1299,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['black', 'nude'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 7,
			name: 'Vega Platform',
			category: 'Platforms',
			description: 'Bold platform shoe for statement looks',
			image: '/images/placeholder.png',
			price: 2799,
			sizes: [36, 37, 38, 39],
			colors: ['black', 'white'],
			heelParams: '14 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 8,
			name: 'Cleo Wedge',
			category: 'Wedges',
			description: 'Comfortable wedge for long walks',
			image: '/images/placeholder.png',
			price: 2199,
			sizes: [37, 38, 39, 40, 41],
			colors: ['beige', 'brown'],
			heelParams: '9 см (Casual)',
			material: 'Suede',
		},
		{
			id: 9,
			name: 'Diana Pump',
			category: 'Pumps',
			description: 'Classic pump with rounded toe',
			image: '/images/placeholder.png',
			price: 2699,
			sizes: [36, 37, 38, 39, 40],
			colors: ['red', 'nude'],
			heelParams: '10 см (Professional)',
			material: 'Patent Leather',
		},
		{
			id: 10,
			name: 'Hera Sandal',
			category: 'Sandals',
			description: 'Strappy sandal for evening events',
			image: '/images/placeholder.png',
			price: 1999,
			sizes: [36, 37, 38, 39],
			colors: ['gold', 'black'],
			heelParams: '8 см (Professional)',
			material: 'Leather',
		},
		{
			id: 11,
			name: 'Maya Boot',
			category: 'Boots',
			description: 'Knee-high boot for cold season',
			image: '/images/placeholder.png',
			price: 5299,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'grey'],
			heelParams: '6 см (Casual)',
			material: 'Leather',
		},
		{
			id: 12,
			name: 'Zara Mule',
			category: 'Mules',
			description: 'Stylish mule with square toe',
			image: '/images/placeholder.png',
			price: 2099,
			sizes: [36, 37, 38, 39, 40],
			colors: ['beige', 'black'],
			heelParams: '6 см (Casual)',
			material: 'Suede',
		},
		{
			id: 13,
			name: 'Nora Flat',
			category: 'Flats',
			description: 'Ballet flat with bow detail',
			image: '/images/placeholder.png',
			price: 1399,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['pink', 'black'],
			heelParams: '1 см (Casual)',
			material: 'Satin',
		},
		{
			id: 14,
			name: 'Lyra Stiletto',
			category: 'Stilettos',
			description: 'Pointed stiletto with ankle strap',
			image: '/images/placeholder.png',
			price: 3499,
			sizes: [36, 37, 38, 39],
			colors: ['black', 'silver'],
			heelParams: '13 см (Professional)',
			material: 'Patent Leather',
		},
		{
			id: 15,
			name: 'Vera Platform',
			category: 'Platforms',
			description: 'Chunky platform with buckle detail',
			image: '/images/placeholder.png',
			price: 2999,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '15 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 16,
			name: 'Aria Wedge',
			category: 'Wedges',
			description: 'Espadrille wedge for summer',
			image: '/images/placeholder.png',
			price: 1799,
			sizes: [37, 38, 39, 40],
			colors: ['white', 'beige'],
			heelParams: '8 см (Casual)',
			material: 'Canvas',
		},
		{
			id: 17,
			name: 'Lena Pump',
			category: 'Pumps',
			description: 'Slingback pump with kitten heel',
			image: '/images/placeholder.png',
			price: 2399,
			sizes: [36, 37, 38, 39, 40],
			colors: ['nude', 'black'],
			heelParams: '6 см (Casual)',
			material: 'Leather',
		},
		{
			id: 18,
			name: 'Mia Sandal',
			category: 'Sandals',
			description: 'Flat sandal with toe ring',
			image: '/images/placeholder.png',
			price: 1199,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['brown', 'tan'],
			heelParams: '2 см (Casual)',
			material: 'Leather',
		},
		{
			id: 19,
			name: 'Tara Boot',
			category: 'Boots',
			description: 'Chelsea boot with elastic sides',
			image: '/images/placeholder.png',
			price: 3899,
			sizes: [37, 38, 39, 40, 41],
			colors: ['black', 'brown'],
			heelParams: '4 см (Casual)',
			material: 'Leather',
		},
		{
			id: 20,
			name: 'Cora Mule',
			category: 'Mules',
			description: 'Feather-trim mule for glam nights',
			image: '/images/placeholder.png',
			price: 2599,
			sizes: [36, 37, 38, 39],
			colors: ['white', 'black'],
			heelParams: '9 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 21,
			name: 'Eva Flat',
			category: 'Flats',
			description: 'Loafer flat with tassel detail',
			image: '/images/placeholder.png',
			price: 1699,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['black', 'brown'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 22,
			name: 'Selene Stiletto',
			category: 'Stilettos',
			description: 'Open-toe stiletto for parties',
			image: '/images/placeholder.png',
			price: 3299,
			sizes: [36, 37, 38, 39],
			colors: ['red', 'gold'],
			heelParams: '12 см (Professional)',
			material: 'Suede',
		},
		{
			id: 23,
			name: 'Bianca Platform',
			category: 'Platforms',
			description: 'Lace-up platform boot',
			image: '/images/placeholder.png',
			price: 3599,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '16 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 24,
			name: 'Rosa Wedge',
			category: 'Wedges',
			description: 'Cork wedge sandal',
			image: '/images/placeholder.png',
			price: 1999,
			sizes: [37, 38, 39, 40],
			colors: ['tan', 'white'],
			heelParams: '10 см (Casual)',
			material: 'Cork',
		},
		{
			id: 25,
			name: 'Clara Pump',
			category: 'Pumps',
			description: 'Block heel pump with square toe',
			image: '/images/placeholder.png',
			price: 2299,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'grey'],
			heelParams: '8 см (Professional)',
			material: 'Leather',
		},
		{
			id: 26,
			name: 'Fiona Sandal',
			category: 'Sandals',
			description: 'Gladiator sandal with wrap-up laces',
			image: '/images/placeholder.png',
			price: 1799,
			sizes: [36, 37, 38, 39, 40],
			colors: ['brown', 'black'],
			heelParams: '3 см (Casual)',
			material: 'Leather',
		},
		{
			id: 27,
			name: 'Jade Boot',
			category: 'Boots',
			description: 'Over-the-knee boot for winter',
			image: '/images/placeholder.png',
			price: 5999,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'grey'],
			heelParams: '7 см (Professional)',
			material: 'Leather',
		},
		{
			id: 28,
			name: 'Sable Mule',
			category: 'Mules',
			description: 'Pointed toe mule with kitten heel',
			image: '/images/placeholder.png',
			price: 2299,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'nude'],
			heelParams: '5 см (Casual)',
			material: 'Patent Leather',
		},
		{
			id: 29,
			name: 'Opal Flat',
			category: 'Flats',
			description: 'Embellished flat with crystal detail',
			image: '/images/placeholder.png',
			price: 1899,
			sizes: [36, 37, 38, 39, 40],
			colors: ['silver', 'gold'],
			heelParams: '1 см (Casual)',
			material: 'Satin',
		},
		{
			id: 30,
			name: 'Petra Stiletto',
			category: 'Stilettos',
			description: 'Transparent stiletto with PVC detail',
			image: '/images/placeholder.png',
			price: 3799,
			sizes: [36, 37, 38, 39],
			colors: ['clear', 'black'],
			heelParams: '14 см (Professional)',
			material: 'PVC',
		},
		{
			id: 31,
			name: 'Alma Platform',
			category: 'Platforms',
			description: 'Retro platform with round toe',
			image: '/images/placeholder.png',
			price: 2699,
			sizes: [36, 37, 38, 39, 40],
			colors: ['white', 'brown'],
			heelParams: '13 см (Professional)',
			material: 'Leather',
		},
		{
			id: 32,
			name: 'Demi Wedge',
			category: 'Wedges',
			description: 'Woven wedge sandal for beach',
			image: '/images/placeholder.png',
			price: 1599,
			sizes: [37, 38, 39, 40, 41],
			colors: ['beige', 'brown'],
			heelParams: '7 см (Casual)',
			material: 'Raffia',
		},
		{
			id: 33,
			name: 'Elsa Pump',
			category: 'Pumps',
			description: 'Two-tone pump with pointed toe',
			image: '/images/placeholder.png',
			price: 2899,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
		{
			id: 34,
			name: 'Gaia Sandal',
			category: 'Sandals',
			description: 'Platform sandal with chunky sole',
			image: '/images/placeholder.png',
			price: 2199,
			sizes: [36, 37, 38, 39, 40],
			colors: ['white', 'black'],
			heelParams: '11 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 35,
			name: 'Halo Boot',
			category: 'Boots',
			description: 'Cowboy boot with embroidered detail',
			image: '/images/placeholder.png',
			price: 6299,
			sizes: [37, 38, 39, 40],
			colors: ['brown', 'tan'],
			heelParams: '5 см (Casual)',
			material: 'Leather',
		},
		{
			id: 36,
			name: 'Ivy Mule',
			category: 'Mules',
			description: 'Clog mule with wooden sole',
			image: '/images/placeholder.png',
			price: 1999,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['brown', 'natural'],
			heelParams: '6 см (Casual)',
			material: 'Leather',
		},
		{
			id: 37,
			name: 'June Flat',
			category: 'Flats',
			description: 'Pointed flat with metallic finish',
			image: '/images/placeholder.png',
			price: 1499,
			sizes: [36, 37, 38, 39, 40],
			colors: ['gold', 'silver'],
			heelParams: '1 см (Casual)',
			material: 'Metallic Leather',
		},
		{
			id: 38,
			name: 'Kaia Stiletto',
			category: 'Stilettos',
			description: 'Caged stiletto with strappy design',
			image: '/images/placeholder.png',
			price: 3599,
			sizes: [36, 37, 38, 39],
			colors: ['black', 'nude'],
			heelParams: '13 см (Professional)',
			material: 'Leather',
		},
		{
			id: 39,
			name: 'Lara Platform',
			category: 'Platforms',
			description: 'Velvet platform with bow detail',
			image: '/images/placeholder.png',
			price: 3199,
			sizes: [36, 37, 38, 39, 40],
			colors: ['burgundy', 'black'],
			heelParams: '14 см (Professional)',
			material: 'Velvet',
		},
		{
			id: 40,
			name: 'Mona Wedge',
			category: 'Wedges',
			description: 'Ankle strap wedge with floral print',
			image: '/images/placeholder.png',
			price: 2099,
			sizes: [37, 38, 39, 40],
			colors: ['multicolor', 'white'],
			heelParams: '9 см (Casual)',
			material: 'Synthetic',
		},
		{
			id: 41,
			name: 'Nina Pump',
			category: 'Pumps',
			description: 'D-orsay pump with cutout sides',
			image: '/images/placeholder.png',
			price: 2599,
			sizes: [36, 37, 38, 39, 40],
			colors: ['nude', 'black'],
			heelParams: '9 см (Professional)',
			material: 'Leather',
		},
		{
			id: 42,
			name: 'Ora Sandal',
			category: 'Sandals',
			description: 'Barely-there sandal with thin straps',
			image: '/images/placeholder.png',
			price: 1699,
			sizes: [36, 37, 38, 39, 40],
			colors: ['silver', 'gold'],
			heelParams: '9 см (Professional)',
			material: 'Leather',
		},
		{
			id: 43,
			name: 'Pola Boot',
			category: 'Boots',
			description: 'Lug sole boot for edgy looks',
			image: '/images/placeholder.png',
			price: 4599,
			sizes: [37, 38, 39, 40, 41],
			colors: ['black', 'white'],
			heelParams: '5 см (Casual)',
			material: 'Synthetic',
		},
		{
			id: 44,
			name: 'Quinn Mule',
			category: 'Mules',
			description: 'Velvet mule with block heel',
			image: '/images/placeholder.png',
			price: 2399,
			sizes: [36, 37, 38, 39, 40],
			colors: ['green', 'navy'],
			heelParams: '7 см (Professional)',
			material: 'Velvet',
		},
		{
			id: 45,
			name: 'Reva Flat',
			category: 'Flats',
			description: 'Classic driving shoe in soft leather',
			image: '/images/placeholder.png',
			price: 1599,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['brown', 'black'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 46,
			name: 'Sora Stiletto',
			category: 'Stilettos',
			description: 'Crystal-embellished stiletto',
			image: '/images/placeholder.png',
			price: 4299,
			sizes: [36, 37, 38, 39],
			colors: ['silver', 'gold'],
			heelParams: '12 см (Professional)',
			material: 'Satin',
		},
		{
			id: 47,
			name: 'Tova Platform',
			category: 'Platforms',
			description: 'Creeper platform with rubber sole',
			image: '/images/placeholder.png',
			price: 2899,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '12 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 48,
			name: 'Uma Wedge',
			category: 'Wedges',
			description: 'Peep-toe wedge with ankle strap',
			image: '/images/placeholder.png',
			price: 2299,
			sizes: [37, 38, 39, 40],
			colors: ['tan', 'black'],
			heelParams: '11 см (Casual)',
			material: 'Leather',
		},
		{
			id: 49,
			name: 'Vita Pump',
			category: 'Pumps',
			description: 'Mary Jane pump with buckle strap',
			image: '/images/placeholder.png',
			price: 2499,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '7 см (Professional)',
			material: 'Patent Leather',
		},
		{
			id: 50,
			name: 'Wren Sandal',
			category: 'Sandals',
			description: 'Thong sandal with beaded detail',
			image: '/images/placeholder.png',
			price: 1299,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['multicolor', 'brown'],
			heelParams: '3 см (Casual)',
			material: 'Leather',
		},
		{
			id: 51,
			name: 'Xena Boot',
			category: 'Boots',
			description: 'Combat boot with multiple buckles',
			image: '/images/placeholder.png',
			price: 4999,
			sizes: [37, 38, 39, 40, 41],
			colors: ['black', 'khaki'],
			heelParams: '4 см (Casual)',
			material: 'Leather',
		},
		{
			id: 52,
			name: 'Yara Mule',
			category: 'Mules',
			description: 'Braided mule with flat sole',
			image: '/images/placeholder.png',
			price: 1799,
			sizes: [36, 37, 38, 39, 40],
			colors: ['tan', 'white'],
			heelParams: '3 см (Casual)',
			material: 'Leather',
		},
		{
			id: 53,
			name: 'Zola Flat',
			category: 'Flats',
			description: 'Woven leather flat sandal',
			image: '/images/placeholder.png',
			price: 1399,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['tan', 'brown'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 54,
			name: 'Abby Stiletto',
			category: 'Stilettos',
			description: 'Satin stiletto for bridal looks',
			image: '/images/placeholder.png',
			price: 3899,
			sizes: [36, 37, 38, 39],
			colors: ['white', 'ivory'],
			heelParams: '11 см (Professional)',
			material: 'Satin',
		},
		{
			id: 55,
			name: 'Bree Platform',
			category: 'Platforms',
			description: 'Glitter platform for party nights',
			image: '/images/placeholder.png',
			price: 3299,
			sizes: [36, 37, 38, 39, 40],
			colors: ['silver', 'gold'],
			heelParams: '15 см (Professional)',
			material: 'Glitter',
		},
		{
			id: 56,
			name: 'Cara Wedge',
			category: 'Wedges',
			description: 'Rope wedge with canvas upper',
			image: '/images/placeholder.png',
			price: 1699,
			sizes: [37, 38, 39, 40],
			colors: ['white', 'navy'],
			heelParams: '8 см (Casual)',
			material: 'Canvas',
		},
		{
			id: 57,
			name: 'Dora Pump',
			category: 'Pumps',
			description: 'Wrap-front pump with tie detail',
			image: '/images/placeholder.png',
			price: 2799,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'red'],
			heelParams: '9 см (Professional)',
			material: 'Suede',
		},
		{
			id: 58,
			name: 'Eden Sandal',
			category: 'Sandals',
			description: 'Flatform sandal with foam sole',
			image: '/images/placeholder.png',
			price: 1499,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['white', 'black'],
			heelParams: '5 см (Casual)',
			material: 'Synthetic',
		},
		{
			id: 59,
			name: 'Faye Boot',
			category: 'Boots',
			description: 'Western boot with pointed toe',
			image: '/images/placeholder.png',
			price: 5499,
			sizes: [37, 38, 39, 40],
			colors: ['brown', 'black'],
			heelParams: '6 см (Casual)',
			material: 'Leather',
		},
		{
			id: 60,
			name: 'Gwen Mule',
			category: 'Mules',
			description: 'Lucite heel mule with clear strap',
			image: '/images/placeholder.png',
			price: 2699,
			sizes: [36, 37, 38, 39, 40],
			colors: ['clear', 'nude'],
			heelParams: '10 см (Professional)',
			material: 'PVC',
		},
		{
			id: 61,
			name: 'Hope Flat',
			category: 'Flats',
			description: 'Slip-on flat with elastic detail',
			image: '/images/placeholder.png',
			price: 1199,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['black', 'white'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 62,
			name: 'Isla Stiletto',
			category: 'Stilettos',
			description: 'Barely-there stiletto sandal',
			image: '/images/placeholder.png',
			price: 3699,
			sizes: [36, 37, 38, 39],
			colors: ['nude', 'silver'],
			heelParams: '13 см (Professional)',
			material: 'Leather',
		},
		{
			id: 63,
			name: 'Juno Platform',
			category: 'Platforms',
			description: 'Sneaker platform with thick sole',
			image: '/images/placeholder.png',
			price: 2499,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['white', 'black'],
			heelParams: '10 см (Casual)',
			material: 'Synthetic',
		},
		{
			id: 64,
			name: 'Kira Wedge',
			category: 'Wedges',
			description: 'Slingback wedge with T-bar strap',
			image: '/images/placeholder.png',
			price: 2099,
			sizes: [37, 38, 39, 40],
			colors: ['beige', 'black'],
			heelParams: '9 см (Casual)',
			material: 'Leather',
		},
		{
			id: 65,
			name: 'Lola Pump',
			category: 'Pumps',
			description: 'Cone heel pump with suede upper',
			image: '/images/placeholder.png',
			price: 2999,
			sizes: [36, 37, 38, 39, 40],
			colors: ['burgundy', 'navy'],
			heelParams: '9 см (Professional)',
			material: 'Suede',
		},
		{
			id: 66,
			name: 'Mara Sandal',
			category: 'Sandals',
			description: 'Jewelled sandal for festive occasions',
			image: '/images/placeholder.png',
			price: 2399,
			sizes: [36, 37, 38, 39, 40],
			colors: ['gold', 'silver'],
			heelParams: '6 см (Professional)',
			material: 'Leather',
		},
		{
			id: 67,
			name: 'Nova Boot',
			category: 'Boots',
			description: 'Sock boot with stretch fabric',
			image: '/images/placeholder.png',
			price: 3499,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'grey'],
			heelParams: '9 см (Professional)',
			material: 'Fabric',
		},
		{
			id: 68,
			name: 'Oona Mule',
			category: 'Mules',
			description: 'Fur-lined mule for winter comfort',
			image: '/images/placeholder.png',
			price: 2199,
			sizes: [36, 37, 38, 39, 40],
			colors: ['grey', 'brown'],
			heelParams: '4 см (Casual)',
			material: 'Fur',
		},
		{
			id: 69,
			name: 'Prue Flat',
			category: 'Flats',
			description: 'Monk strap flat with double buckle',
			image: '/images/placeholder.png',
			price: 1799,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['black', 'brown'],
			heelParams: '1 см (Casual)',
			material: 'Leather',
		},
		{
			id: 70,
			name: 'Rhea Stiletto',
			category: 'Stilettos',
			description: 'Snake print stiletto',
			image: '/images/placeholder.png',
			price: 3999,
			sizes: [36, 37, 38, 39],
			colors: ['snake', 'black'],
			heelParams: '12 см (Professional)',
			material: 'Exotic Leather',
		},
		{
			id: 71,
			name: 'Sara Platform',
			category: 'Platforms',
			description: 'Wooden platform sandal',
			image: '/images/placeholder.png',
			price: 2799,
			sizes: [36, 37, 38, 39, 40],
			colors: ['natural', 'black'],
			heelParams: '13 см (Professional)',
			material: 'Leather',
		},
		{
			id: 72,
			name: 'Thea Wedge',
			category: 'Wedges',
			description: 'Suede wedge with fringe detail',
			image: '/images/placeholder.png',
			price: 2299,
			sizes: [37, 38, 39, 40],
			colors: ['tan', 'brown'],
			heelParams: '8 см (Casual)',
			material: 'Suede',
		},
		{
			id: 73,
			name: 'Una Pump',
			category: 'Pumps',
			description: 'Bow-detailed pump in satin',
			image: '/images/placeholder.png',
			price: 2699,
			sizes: [36, 37, 38, 39, 40],
			colors: ['pink', 'black'],
			heelParams: '10 см (Professional)',
			material: 'Satin',
		},
		{
			id: 74,
			name: 'Vivi Sandal',
			category: 'Sandals',
			description: 'Ankle wrap sandal with block heel',
			image: '/images/placeholder.png',
			price: 1899,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '7 см (Professional)',
			material: 'Leather',
		},
		{
			id: 75,
			name: 'Willa Boot',
			category: 'Boots',
			description: 'Rain boot with rubber sole',
			image: '/images/placeholder.png',
			price: 2999,
			sizes: [37, 38, 39, 40, 41],
			colors: ['black', 'red'],
			heelParams: '2 см (Casual)',
			material: 'Rubber',
		},
		{
			id: 76,
			name: 'Xara Mule',
			category: 'Mules',
			description: 'Satin mule with feather trim',
			image: '/images/placeholder.png',
			price: 2899,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'white'],
			heelParams: '8 см (Professional)',
			material: 'Satin',
		},
		{
			id: 77,
			name: 'Yola Flat',
			category: 'Flats',
			description: 'Espadrille flat with jute sole',
			image: '/images/placeholder.png',
			price: 1299,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['white', 'navy'],
			heelParams: '2 см (Casual)',
			material: 'Canvas',
		},
		{
			id: 78,
			name: 'Zara Stiletto',
			category: 'Stilettos',
			description: 'Floral applique stiletto',
			image: '/images/placeholder.png',
			price: 4199,
			sizes: [36, 37, 38, 39],
			colors: ['multicolor', 'black'],
			heelParams: '11 см (Professional)',
			material: 'Fabric',
		},
		{
			id: 79,
			name: 'Alma Wedge',
			category: 'Wedges',
			description: 'Leather wedge with metal detail',
			image: '/images/placeholder.png',
			price: 2499,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'gold'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
		{
			id: 80,
			name: 'Bela Pump',
			category: 'Pumps',
			description: 'Croc embossed pump',
			image: '/images/placeholder.png',
			price: 3099,
			sizes: [36, 37, 38, 39, 40],
			colors: ['beige', 'black'],
			heelParams: '9 см (Professional)',
			material: 'Embossed Leather',
		},
		{
			id: 81,
			name: 'Caia Sandal',
			category: 'Sandals',
			description: 'Raffia sandal with pompom detail',
			image: '/images/placeholder.png',
			price: 1399,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['multicolor', 'natural'],
			heelParams: '3 см (Casual)',
			material: 'Raffia',
		},
		{
			id: 82,
			name: 'Dani Boot',
			category: 'Boots',
			description: 'Studded ankle boot',
			image: '/images/placeholder.png',
			price: 4799,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'silver'],
			heelParams: '5 см (Casual)',
			material: 'Leather',
		},
		{
			id: 83,
			name: 'Ellie Mule',
			category: 'Mules',
			description: 'Padded sole mule for comfort',
			image: '/images/placeholder.png',
			price: 1899,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['white', 'black'],
			heelParams: '4 см (Casual)',
			material: 'Leather',
		},
		{
			id: 84,
			name: 'Fara Flat',
			category: 'Flats',
			description: 'Tie-up flat with ribbon lace',
			image: '/images/placeholder.png',
			price: 1599,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'pink'],
			heelParams: '1 см (Casual)',
			material: 'Satin',
		},
		{
			id: 85,
			name: 'Gala Stiletto',
			category: 'Stilettos',
			description: 'Leopard print stiletto',
			image: '/images/placeholder.png',
			price: 3799,
			sizes: [36, 37, 38, 39],
			colors: ['leopard', 'black'],
			heelParams: '13 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 86,
			name: 'Hana Platform',
			category: 'Platforms',
			description: 'Floral platform with wedge heel',
			image: '/images/placeholder.png',
			price: 2599,
			sizes: [36, 37, 38, 39, 40],
			colors: ['multicolor', 'white'],
			heelParams: '12 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 87,
			name: 'Iola Wedge',
			category: 'Wedges',
			description: 'Wedge sneaker with lace-up front',
			image: '/images/placeholder.png',
			price: 2199,
			sizes: [37, 38, 39, 40, 41],
			colors: ['white', 'black'],
			heelParams: '7 см (Casual)',
			material: 'Leather',
		},
		{
			id: 88,
			name: 'Jana Pump',
			category: 'Pumps',
			description: 'Peep-toe pump with ankle strap',
			image: '/images/placeholder.png',
			price: 2799,
			sizes: [36, 37, 38, 39, 40],
			colors: ['nude', 'red'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
		{
			id: 89,
			name: 'Kola Sandal',
			category: 'Sandals',
			description: 'Flatform slide with quilted upper',
			image: '/images/placeholder.png',
			price: 1799,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['black', 'beige'],
			heelParams: '4 см (Casual)',
			material: 'Leather',
		},
		{
			id: 90,
			name: 'Laya Boot',
			category: 'Boots',
			description: 'Zip-up boot with pointed toe',
			image: '/images/placeholder.png',
			price: 4299,
			sizes: [37, 38, 39, 40],
			colors: ['black', 'nude'],
			heelParams: '8 см (Professional)',
			material: 'Patent Leather',
		},
		{
			id: 91,
			name: 'Mela Mule',
			category: 'Mules',
			description: 'Transparent mule with clear heel',
			image: '/images/placeholder.png',
			price: 2499,
			sizes: [36, 37, 38, 39, 40],
			colors: ['clear', 'black'],
			heelParams: '9 см (Professional)',
			material: 'PVC',
		},
		{
			id: 92,
			name: 'Nala Flat',
			category: 'Flats',
			description: 'Knitted flat with sock-like fit',
			image: '/images/placeholder.png',
			price: 1299,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['grey', 'black'],
			heelParams: '1 см (Casual)',
			material: 'Knit',
		},
		{
			id: 93,
			name: 'Orla Stiletto',
			category: 'Stilettos',
			description: 'Zebra print stiletto',
			image: '/images/placeholder.png',
			price: 3599,
			sizes: [36, 37, 38, 39],
			colors: ['zebra', 'black'],
			heelParams: '12 см (Professional)',
			material: 'Synthetic',
		},
		{
			id: 94,
			name: 'Peri Platform',
			category: 'Platforms',
			description: 'Patent platform with chain detail',
			image: '/images/placeholder.png',
			price: 3399,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'gold'],
			heelParams: '14 см (Professional)',
			material: 'Patent Leather',
		},
		{
			id: 95,
			name: 'Runa Wedge',
			category: 'Wedges',
			description: 'Macrame wedge sandal',
			image: '/images/placeholder.png',
			price: 1899,
			sizes: [37, 38, 39, 40],
			colors: ['natural', 'white'],
			heelParams: '8 см (Casual)',
			material: 'Macrame',
		},
		{
			id: 96,
			name: 'Sela Pump',
			category: 'Pumps',
			description: 'Velvet pump with jewel heel',
			image: '/images/placeholder.png',
			price: 3199,
			sizes: [36, 37, 38, 39, 40],
			colors: ['emerald', 'navy'],
			heelParams: '10 см (Professional)',
			material: 'Velvet',
		},
		{
			id: 97,
			name: 'Tina Sandal',
			category: 'Sandals',
			description: 'Crisscross sandal with block heel',
			image: '/images/placeholder.png',
			price: 1999,
			sizes: [36, 37, 38, 39, 40],
			colors: ['tan', 'black'],
			heelParams: '7 см (Professional)',
			material: 'Leather',
		},
		{
			id: 98,
			name: 'Ulla Boot',
			category: 'Boots',
			description: 'Shearling lined boot for winter',
			image: '/images/placeholder.png',
			price: 6499,
			sizes: [37, 38, 39, 40],
			colors: ['brown', 'grey'],
			heelParams: '3 см (Casual)',
			material: 'Shearling',
		},
		{
			id: 99,
			name: 'Vela Mule',
			category: 'Mules',
			description: 'Laser-cut mule with geometric pattern',
			image: '/images/placeholder.png',
			price: 2299,
			sizes: [36, 37, 38, 39, 40],
			colors: ['white', 'black'],
			heelParams: '6 см (Professional)',
			material: 'Leather',
		},
		{
			id: 100,
			name: 'Wova Flat',
			category: 'Flats',
			description: 'Recycled material flat for eco lovers',
			image: '/images/placeholder.png',
			price: 1499,
			sizes: [36, 37, 38, 39, 40, 41],
			colors: ['green', 'natural'],
			heelParams: '1 см (Casual)',
			material: 'Recycled',
		},
		{
			id: 101,
			name: 'Scarlett Pump',
			category: 'Pumps',
			description: 'Elegant pump for evening events',
			image: '/images/placeholder.png',
			price: 1999,
			oldPrice: 2499,
			discountPercent: 20,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'red'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
		{
			id: 102,
			name: 'Scarlett Pump',
			category: 'Pumps',
			description: 'Elegant pump for evening events',
			image: '/images/placeholder.png',
			price: 1999,
			oldPrice: 0,
			discountPercent: 0,
			sizes: [36, 37, 38, 39, 40],
			colors: ['black', 'red'],
			heelParams: '10 см (Professional)',
			material: 'Leather',
		},
	];

	const totalProduct = 101;
	const totalPages = Math.ceil((totalProduct ?? 0) / BASE_LIMIT);

	const limit = Number(searchParams.limit) || 24;
	const currentPage = Number(searchParams.page) || 1;

	const skippedProducts = (currentPage - 1) * BASE_LIMIT;

	//! const remainingOnPage =
	//! 	(totalProduct ?? 0) - skipped - (products?.length ?? 0);
	const remainingProductsOnPage = (totalProduct ?? 0) - skippedProducts - 24;

	const hasMore = remainingProductsOnPage > 0;

	return (
		<div>
			<div className={styles['product-list']}>
				{products.map(product => (
					<ProductCard
						product={product}
						key={product.id}
					/>
				))}
			</div>
			{hasMore && (
				<div className={styles['button-load-more-wrapper']}>
					<LoadMoreButton currentLimit={limit} />
				</div>
			)}
			<CatalogPagination
				currentPage={currentPage}
				totalPages={totalPages}
			/>
		</div>
	);
}
